using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class VRAvatarCalibratorModel
{
    [RealtimeProperty(1, true, true)]
    private Vector3 _avatarScale;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class VRAvatarCalibratorModel : RealtimeModel {
    public UnityEngine.Vector3 avatarScale {
        get {
            return _avatarScaleProperty.value;
        }
        set {
            if (_avatarScaleProperty.value == value) return;
            _avatarScaleProperty.value = value;
            InvalidateReliableLength();
            FireAvatarScaleDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(VRAvatarCalibratorModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector3> avatarScaleDidChange;
    
    public enum PropertyID : uint {
        AvatarScale = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _avatarScaleProperty;
    
    #endregion
    
    public VRAvatarCalibratorModel() : base(null) {
        _avatarScaleProperty = new ReliableProperty<UnityEngine.Vector3>(1, _avatarScale);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _avatarScaleProperty.UnsubscribeCallback();
    }
    
    private void FireAvatarScaleDidChange(UnityEngine.Vector3 value) {
        try {
            avatarScaleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _avatarScaleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _avatarScaleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.AvatarScale: {
                    changed = _avatarScaleProperty.Read(stream, context);
                    if (changed) FireAvatarScaleDidChange(avatarScale);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _avatarScale = avatarScale;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
