using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;
using Normal.Realtime.Collections;

[RealtimeModel]
public partial class GameButtonModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<StartToggleDicModel> _d_GameStartToggle;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GameButtonModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<StartToggleDicModel> d_GameStartToggle {
        get => _d_GameStartToggle;
    }
    
    public enum PropertyID : uint {
        D_GameStartToggle = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<StartToggleDicModel>> _d_GameStartToggleProperty;
    
    #endregion
    
    public GameButtonModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _d_GameStartToggle = new Normal.Realtime.Serialization.RealtimeDictionary<StartToggleDicModel>();
        childModels[0] = _d_GameStartToggle;
        
        SetChildren(childModels);
        
        _d_GameStartToggleProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<StartToggleDicModel>>(1, _d_GameStartToggle);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _d_GameStartToggleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _d_GameStartToggleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.D_GameStartToggle: {
                    changed = _d_GameStartToggleProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _d_GameStartToggle = d_GameStartToggle;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
